# Generated by Django 4.2 on 2023-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teacher', 'teacher'), ('Student', 'student')], default='Student', max_length=7, verbose_name='роль'),
        ),
    ]
