# Generated by Django 4.2 on 2023-07-28 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='дата сдачи')),
                ('appointor_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher', verbose_name='назначивший')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='студент')),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'группа задач',
                'verbose_name_plural': 'группы задач',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('status', models.CharField(choices=[('RJ', 'Rejected'), ('AC', 'Accepted')], default='RJ', max_length=2, verbose_name='статус')),
                ('appointor_teachers', models.ManyToManyField(related_name='appointed_tasks', through='tasks.AppointedTask', to='users.teacher', verbose_name='назначившие')),
                ('producer_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_tasks', to='users.teacher', verbose_name='создавший')),
                ('students', models.ManyToManyField(related_name='tasks', through='tasks.AppointedTask', to='users.student', verbose_name='студенты')),
                ('task_groups', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.taskgroup', verbose_name='группы задач')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='задача'),
        ),
    ]
